version: '3.2'

services:
  proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'reverse-proxy'
    ports:
      - '${PORT}:80'
    volumes:
      - './proxy/vhosts:/etc/nginx/vhost.d'
      - './proxy/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './proxy/certs:/etc/nginx/certs'

  ## статика
  static-proxy:
    image: nginx
    container_name: static-proxy
    volumes:
      - './static/proxy/conf:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${FRONTEND}"
    links:
      - node-cli
    volumes_from:
      - node-cli

  node-cli:
    container_name: node-cli
    build:
      context: ./static
    volumes:
      - '../frontend:/usr/share/nginx/html'
    ports:
      - "4000:4000"
    command: bash -c  "${FRONTEND_DEPLOY_SCRIPT}"

  # прокси для пхп
  php-proxy:
    image: nginx
    container_name: php-proxy
    volumes:
      - './php/proxy/conf:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${BACKEND}"
    links:
      - php
    volumes_from:
      - php

  php:
    container_name: php
    build:
       context: ./php/
    volumes:
      - '../backend:/var/www/html'

  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

### тут происходит подгрузка зависимостей для бека и фронта
  php-cli:
    container_name: php-cli
    build:
      context: ./php/
    volumes:
      - "../backend:/var/www/html"
    command: bash -c  "${BACKEND_DEPLOY_SCRIPT}"
