version: '2'

services:
  proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'proxy'
    ports:
      - '80:80'
    volumes:
      - './nginx/vhosts:/etc/nginx/vhost.d'
      - './nginx/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './nginx/certs:/etc/nginx/certs'

  app1:
    image: nginx
    container_name: js
    volumes:
      - '../frontend:/usr/share/nginx/html'
    environment:
      VIRTUAL_HOST: lit.my

  app2:
    image: php:7.3-fpm
    container_name: php
    volumes:
      - '../backend:/var/www/html/'
    environment:
      VIRTUAL_HOST: api.lit.my
      VIRTUAL_ROOT: '/web'