version: '2'

services:
  proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'proxy'
    ports:
      - '81:80'
    volumes:
      - './nginx/vhosts:/etc/nginx/vhost.d'
      - './nginx/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './nginx/certs:/etc/nginx/certs'

  nginx1:
    image: nginx
    container_name: nginx-static
    volumes:
      - '../frontend:/usr/share/nginx/html'
    environment:
      VIRTUAL_HOST: lit.my

#    networks:
#      - proxy

  nginx2:
    image: nginx
    container_name: nginx-php
    volumes:
      - './nginx/config.yii2:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: api.lit.my
    links:
      - php
    volumes_from:
      - php

  php:
    image: php:7.3-fpm
    container_name: php
    volumes:
      - '../backend:/var/www/'