version: '3.2'

services:
  reverse-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'reverse-proxy'
    ports:
      - '${PORT}:80'
    volumes:
      - './proxy/vhosts:/etc/nginx/vhost.d'
      - './proxy/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './proxy/certs:/etc/nginx/certs'

  ## статика
  nuxt-proxy:
    image: nginx
    container_name: "nuxt-proxy"
    volumes:
      - './nuxt/proxy/conf:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${FRONTEND}"
    links:
      - nuxt-js
    volumes_from:
      - nuxt-js

  nuxt-js:
    container_name: "nuxt-js"
    image: node:latest
    working_dir: "/app"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      HOST: 0.0.0.0
      PORT: 4000
    volumes:
      - '../frontend:/app'
    ports:
      - "4000:4000"
    command: bash -c  "${FRONTEND_DEPLOY_SCRIPT}"

  # прокси для пхп
  php-proxy:
    image: nginx
    container_name: "php-proxy"
    volumes:
      - './php/proxy/conf:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${BACKEND}"
    links:
      - php
    volumes_from:
      - php

  php:
    container_name: "php"
    build:
       context: ./php/
    volumes:
      - '../backend:/var/www/html'

  mysql:
    image: mysql:5.7
    container_name: "mysql"
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

### тут происходит подгрузка зависимостей для бека и фронта
  php-cli:
    container_name: "php-cli"
    build:
      context: ./php/
    volumes:
      - "../backend:/var/www/html"
    command: bash -c  "${BACKEND_DEPLOY_SCRIPT}"
